copernicusmarine/core_functions/services_utils.py, copernicusmarine/download_functions/download_arco_series.py, copernicusmarine/download_functions/subset_xarray.py, copernicusmarine/python_interface/load_utils.py, tests/test_command_line_interface.py, tests/test_python_interface.py
=> CMCS-306-support of retention periods for python api feature of arco

copernicusmarine/core_functions/subset.py, copernicusmarine/download_functions/download_ftp.py, copernicusmarine/download_functions/download_get.py, copernicusmarine/download_functions/download_original_files.py, tests/test_command_line_interface.py, tests/test_request_files.py
=> fix: smoothly exit when downloading file list

copernicusmarine/core_functions/sessions.py
=> fix: add event loop when opening session

copernicusmarine/core_functions/deprecated.py, copernicusmarine/core_functions/deprecated_options.py, copernicusmarine/python_interface/get.py
@nitreb what do you think? I don't like it much! It fixes the current problem. 
Do you have otherwise an idea how we could do deprecated options in python without them being replaced?
=> fix: dowload file list not overwritten by create file list

copernicusmarine/core_functions/credentials_utils.py
fix [CMCS-351](https://mercator-ocean.atlassian.net/browse/CMCS-351)
=> chore: change my.cmems-du.eu to nrt.cmems-du.eu for credentials

conda_environment_test.yaml, tests/test_command_line_interface.py
@renaudjester is that something like this that you had in mind?
=> Fix cache issue by running the test that overwrite metadata cache first

copernicusmarine/catalogue_parser/catalogue_parser.py
Relates to [CMCS-193](https://mercator-ocean.atlassian.net/browse/CMCS-193)
=> Add more explicit message when catalog parsing fails

copernicusmarine/download_functions/download_arco_series.py, copernicusmarine/download_functions/subset_xarray.py, copernicusmarine/download_functions/utils.py, tests/test_command_line_interface.py, tests/test_command_line_interface_nearest_layer_subset.py
Related to error [CMCS-313](https://mercator-ocean.atlassian.net/browse/CMCS-313). 
Changed dataset.dims to dataset.sizes for the update on the xarray method.
=> Changed to dataset.sizes

copernicusmarine/download_functions/common_download.py, tests/test_python_interface.py
=> fix: fillvalue for depth was nan

poetry.lock, pyproject.toml
fix [CMT-71](https://cms-change.atlassian.net/browse/CMT-71)
=> fix: numpy 2.0.0 unsupported

.github/workflows/tests.yml
To be able to trigger the tests when we do Pull request on the v2 branch
=> test: trigger tests on v2 branch

copernicusmarine/catalogue_parser/catalogue_parser.py, copernicusmarine/core_functions/describe.py, copernicusmarine/download_functions/download_arco_series.py, copernicusmarine/download_functions/subset_xarray.py, tests/test_command_line_interface.py, tests/test_python_interface.py
Trying to merge into the version 2 of the toolbox. Adapting the output file to be compatible with the netcdf standards.
=> chore: updating the attributes for the variables, coordinates and dataset

copernicusmarine/download_functions/download_original_files.py, tests/test_command_line_interface.py, tests/test_python_interface.py
fix https://cms-change.atlassian.net/browse/CMT-42
=> fix: if not permission modifie last updated date on file continue

copernicusmarine/download_functions/subset_xarray.py, test.py, tests/test_command_line_interface.py, tests/test_warnings_subset_bounds.py
fix: [CMT-54](https://cms-change.atlassian.net/browse/CMT-54)
=> Consider longitude edge point as same

.github/workflows/pre-release.yml, Makefile, pre-release.sh
=> chore: add way to do pre releases

copernicusmarine/catalogue_parser/catalogue_parser.py, copernicusmarine/core_functions/credentials_utils.py, tests/test_command_line_interface.py
fix part of [CMT-22](https://cms-change.atlassian.net/browse/CMT-122)
=> fix: no mention of STAC or CMEMS

copernicusmarine/catalogue_parser/catalogue_parser.py
We detected a bug [CMT-126](https://cms-change.atlassian.net/browse/CMT-126) with the describe with the pre-release.
Although I solved it in my working branch, I think that maybe creating it with another branch and having it more clear in the release notes will be easier and clearer for the users and for us.
=> fix: describe bug

README.md, doc/usage/shared-options.rst
I was going through the word again and I found that maybe these things weren't adressed, don't know if it is worth merging some of them or if we consider that it was actually okay as they were!
=> fix: small changes docs

doc/usage/shared-options.rst
a small update that maybe makes life easier for the users (?) Tell me if you think it is better this way.
=> chore: checking examples

copernicusmarine/__init__.py, copernicusmarine/core_functions/credentials_utils.py, copernicusmarine/core_functions/login.py, doc/usage/errors.rst, doc/usage/login-usage.rst, tests/test_login.py
[Fix CMT-4](https://cms-change.atlassian.net/browse/CMT-4)
=> feat: support the new authentification system

.github/workflows/check-format.yml
Check format workflow on github machines and should now run with forks
=> test: update check format workflow

copernicusmarine/__init__.py, copernicusmarine/core_functions/utils.py, copernicusmarine/core_functions/versions_verifier.py, copernicusmarine/logger.py, copernicusmarine/versioner.py, pyproject.toml
From #178 and #167! Thanks again :D 
The tests should be fix for future PR's from forks
=> chore: several updated from users

.github/workflows/check-format.yml, .github/workflows/release.yml, .github/workflows/tests.yml, CONTRIBUTION.md, release.sh
Need to update the release process to go with the release stratagy: main branch with main development and `release/v1` branch for maintenance
=> chore: update release process for new branching strat (#192)

.github/workflows/check-format.yml, .github/workflows/link-PR-doc.yml, conda_environment_sphinx.yaml, doc/usage/quickoverview.ipynb
=> fix: add myst-nb as dependency

copernicusmarine/core_functions/get.py, copernicusmarine/core_functions/services_utils.py, tests/test_command_line_interface.py, tests/test_dataset_part_selection.py, tests/test_get_sync.py
fix [CMT-151](https://cms-change.atlassian.net/browse/CMT-151) by letting users use the `--sync` option with dataset with parts
=> fix: sync available for datasets with parts

.github/workflows/release.yml
Correction to be able to select the right branch
=> Copernicus Marine Release 1.3.5

tests/test_describe.py
correcting the tests so that we don't have problems with the toolbox implementation after the release.
----
📚 Documentation preview 📚: https://copernicusmarine--235.org.readthedocs.build/en/235/
=> chore: correcting the tests

copernicusmarine/catalogue_parser/catalogue_parser.py, copernicusmarine/core_functions/credentials_utils.py, copernicusmarine/core_functions/sessions.py, copernicusmarine/core_functions/versions_verifier.py, tests/resources/mock_stac_catalog/marine_data_store_stac_metadata_mock.py
fix [CMT-149](https://cms-change.atlassian.net/browse/CMT-149)
----
📚 Documentation preview 📚: https://copernicusmarine--232.org.readthedocs.build/en/232/
=> chore: add raise for status for better error messages

copernicusmarine/__init__.py, copernicusmarine/command_line_interface/group_describe.py, copernicusmarine/command_line_interface/group_get.py, copernicusmarine/command_line_interface/group_subset.py, copernicusmarine/core_functions/fields_query_builder.py, tests/test_command_line_interface.py, tests/test_describe.py, tests/test_describe_released_date.py
Fix [CMT-150 ](https://cms-change.atlassian.net/browse/CMT-150)
If user inputs only wrong fields => Error where we print the available fields (Custom error) 
If user input some wrong fields => Logger warning where we print the available fields
----
📚 Documentation preview 📚: https://copernicusmarine--237.org.readthedocs.build/en/237/
=> chore: verify the requested fields and return list of available ones

copernicusmarine/catalogue_parser/catalogue_parser.py, copernicusmarine/download_functions/utils.py
Fix [CMT-166](https://cms-change.atlassian.net/browse/CMT-166) and [CMT-168](https://cms-change.atlassian.net/browse/CMT-168)
----
📚 Documentation preview 📚: https://copernicusmarine--239.org.readthedocs.build/en/239/
=> fix: filter precisely id and jump unknown dimensions

copernicusmarine/command_line_interface/group_get.py, copernicusmarine/command_line_interface/group_subset.py, copernicusmarine/core_functions/credentials_utils.py, copernicusmarine/core_functions/get.py, copernicusmarine/core_functions/models.py, copernicusmarine/core_functions/services_utils.py, copernicusmarine/core_functions/subset.py, copernicusmarine/core_functions/versions_verifier.py, copernicusmarine/download_functions/download_arco_series.py, copernicusmarine/download_functions/download_original_files.py, copernicusmarine/download_functions/utils.py, tests/__snapshots__/test_query_builder.ambr, tests/test_command_line_interface.py, tests/test_dataset_part_selection.py, tests/test_dataset_version_selection.py, tests/test_get_direct_download.py, tests/test_get_index_files_insitu.py, tests/test_login.py, tests/test_request_files.py, tests/test_service_selection_arco.py, tests/test_warnings_subset_bounds.py
fix [CMT-132](https://cms-change.atlassian.net/browse/CMT-132)
fix [CMT-138](https://cms-change.atlassian.net/browse/CMT-138)
fix [CMT-153](https://cms-change.atlassian.net/browse/CMT-153)
----
📚 Documentation preview 📚: https://copernicusmarine--244.org.readthedocs.build/en/244/
=> chore: clean logs

copernicusmarine/catalogue_parser/catalogue_parser.py
fix [CMT-167](https://cms-change.atlassian.net/browse/CMT-167)
Dataset mapping can now have comma separated products for a dataset
----
📚 Documentation preview 📚: https://copernicusmarine--247.org.readthedocs.build/en/247/
=> chore: multiple products for a dataset in the mapping

copernicusmarine/command_line_interface/group_get.py, copernicusmarine/command_line_interface/group_subset.py, copernicusmarine/command_line_interface/utils.py, copernicusmarine/core_functions/deprecated_options.py, tests/test_deprecated_options.py
fix [CMT-176](https://cms-change.atlassian.net/browse/CMT-176)
----
📚 Documentation preview 📚: https://copernicusmarine--253.org.readthedocs.build/en/253/
=> feat: force download has no effect but does not raise

pyproject.toml
----
📚 Documentation preview 📚: https://copernicusmarine--258.org.readthedocs.build/en/258/
=> Copernicus Marine Release 2.0.0

pyproject.toml, release.sh
----
📚 Documentation preview 📚: https://copernicusmarine--269.org.readthedocs.build/en/269/
=> Copernicus Marine Release 1.3.6

copernicusmarine/download_functions/subset_xarray.py, copernicusmarine/download_functions/utils.py, tests/test_command_line_interface.py
There was a bug reported in #272 . This PR addresses it, trying to improve the performance of the code (not actually giving any error message).
It was a pretty edge case, where the expected values for the subset were just outside the values, creating a weird interaction with another function (calculating the correct chunking).
It also made me realise there was a mistake when calculating the 'nearest', the window wasn't moving as it should. Now everything should work.
fix [CMT-194](https://cms-change.atlassian.net/browse/CMT-194)
----
📚 Documentation preview 📚: https://copernicusmarine--273.org.readthedocs.build/en/273/
=> [subset] Solving bug #272

.flake8, conda_environment_sphinx.yaml, doc/conf.py, doc/installation.rst
Fixes [CMT-197](https://cms-change.atlassian.net/browse/CMT-197)
----
📚 Documentation preview 📚: https://copernicusmarine--278.org.readthedocs.build/en/278/
=> dynamically use version in binaries links

pyproject.toml
----
📚 Documentation preview 📚: https://copernicusmarine--280.org.readthedocs.build/en/280/
=> Copernicus Marine Release 2.0.1

doc/changelog/changelog.rst, doc/changelog/v210a0.rst, doc/usage/subset-usage.rst, pyproject.toml
----
📚 Documentation preview 📚: https://copernicusmarine--293.org.readthedocs.build/en/293/
=> Copernicus Marine Pre-Release 2.1.0a0

copernicusmarine/catalogue_parser/models.py, copernicusmarine/python_interface/subset.py, doc/usage/describe-usage.rst, doc/usage/stereo_subset.ipynb, doc/usage/subset-usage.rst, doc/usage/subset_using_polygons.ipynb
From the comments about the alpha version
----
📚 Documentation preview 📚: https://copernicusmarine--299.org.readthedocs.build/en/299/
=> fix: update docs

copernicusmarine/download_functions/download_zarr.py, copernicusmarine/download_functions/utils.py
Updating a way to handle naming. Correcting also a mini small bug but that it seemed quite relevant 🥺 .
Let me know if you think the correction of the bug is also breaking change... I consider it to be relevant enough but it might be maybe!
----
📚 Documentation preview 📚: https://copernicusmarine--303.org.readthedocs.build/en/303/
=> [fix] Update way to handle naming

doc/changelog/changelog.rst, doc/changelog/v210b1.rst, doc/usage/describe-usage.rst, pyproject.toml
----
📚 Documentation preview 📚: https://copernicusmarine--308.org.readthedocs.build/en/308/
=> Copernicus Marine Pre-Release 2.1.0b1

copernicusmarine/core_functions/credentials_utils.py, copernicusmarine/core_functions/login.py, tests/resources/mock_stac_catalog/marine_data_store_stac_metadata_mock.py
Fixes [CMT-213](https://cms-change.atlassian.net/browse/CMT-213)
----
📚 Documentation preview 📚: https://copernicusmarine--306.org.readthedocs.build/en/306/
=> properly assign username

doc/usage/stereo_subset.ipynb
We introduce some little suggestions to improve the presentation.
----
📚 Documentation preview 📚: https://copernicusmarine--309.org.readthedocs.build/en/309/
=> [upgrade] improve documentation with suggestions

doc/changelog/changelog.rst, doc/changelog/v210.rst, doc/usage/describe-usage.rst, pyproject.toml
----
📚 Documentation preview 📚: https://copernicusmarine--321.org.readthedocs.build/en/321/
=> Copernicus Marine Release 2.1.0

copernicusmarine/download_functions/utils.py
This reverts commit 4803f8409f7aebb0d0ff03834c51d2cb200b2f88.
----
📚 Documentation preview 📚: https://copernicusmarine--326.org.readthedocs.build/en/326/
=> Revert "CCM-842 (#324)"

doc/installation.rst
For the examples with binaries to be more user friendly and human readable
----
📚 Documentation preview 📚: https://copernicusmarine--335.org.readthedocs.build/en/335/
=> doc: improve binaries doc examples

copernicusmarine/download_functions/download_sparse.py, copernicusmarine/download_functions/subset_xarray.py, copernicusmarine/python_interface/load_utils.py, doc/changelog/changelog.rst, doc/changelog/v211.rst, tests/test_sparse_subset.py
fix [CMT-233](https://cms-change.atlassian.net/browse/CMT-233)
----
📚 Documentation preview 📚: https://copernicusmarine--329.org.readthedocs.build/en/329/
[CMT-233]: https://cms-change.atlassian.net/browse/CMT-233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: return empty dataframe if no data

doc/changelog/v211.rst, doc/installation.rst, pyproject.toml
----
📚 Documentation preview 📚: https://copernicusmarine--337.org.readthedocs.build/en/337/
=> Copernicus Marine Release 2.1.1

doc/changelog/v211.rst
----
📚 Documentation preview 📚: https://copernicusmarine--338.org.readthedocs.build/en/338/
=> doc: change log title

copernicusmarine/catalogue_parser/catalogue_parser.py, copernicusmarine/catalogue_parser/models.py, copernicusmarine/core_functions/services_utils.py, copernicusmarine/core_functions/subset.py, copernicusmarine/download_functions/download_sparse.py, copernicusmarine/python_interface/load_utils.py, doc/usage/subset-usage.rst, tests/__snapshots__/test_describe_released_date.ambr, tests/test_describe.py, tests/test_versions_parts_sorting.py
Fix [CMT-230](https://cms-change.atlassian.net/browse/CMT-230)
----
📚 Documentation preview 📚: https://copernicusmarine--327.org.readthedocs.build/en/327/
[CMT-230]: https://cms-change.atlassian.net/browse/CMT-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add product doi as column and product doi at dataset metadata level

tests/resources/file_list_examples/file_list_example.txt, tests/test_command_line_interface.py
Updating the tests in main so we don't need to create all commits from the different branches.
----
📚 Documentation preview 📚: https://copernicusmarine--356.org.readthedocs.build/en/356/
=> test-fix: correcting the tests

poetry.lock, pyproject.toml, tests/__snapshots__/test_dependencies_updates.ambr, tests/test_sparse_subset.py
fix [CMT-283](https://cms-change.atlassian.net/browse/CMT-283) (bug 15) 
[CMT-283]: https://cms-change.atlassian.net/browse/CMT-283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
----
📚 Documentation preview 📚: https://copernicusmarine--360.org.readthedocs.build/en/360/
=> fix: use newer version of arcosparse with bug fix

doc/changelog/changelog.rst, doc/changelog/v220b0.rst, doc/installation.rst, pyproject.toml
Please be aware that merging this PR will trigger the pre-release process. Please check the following elements:
Please do not target 'main' as the changelog will not be kept for the release.
----
📚 Documentation preview 📚: https://copernicusmarine--362.org.readthedocs.build/en/362/
=> Copernicus Marine Toolbox Pre-Release v2.2.0b0

codecov.yml, copernicusmarine/download_functions/download_zarr.py, copernicusmarine/download_functions/subset_xarray.py, copernicusmarine/python_interface/load_utils.py, doc/changelog/v220b0.rst, doc/usage/subset-usage.rst, pyproject.toml, tests/test_originalGrid_datasets.py
Please be aware that merging this PR will trigger the pre-release process. Please check the following elements:
Please do not target 'main' as the changelog will not be kept for the release.
----
📚 Documentation preview 📚: https://copernicusmarine--366.org.readthedocs.build/en/366/
=> Copernicus Marine Toolbox Pre-Release v2.2.0b1

copernicusmarine/download_functions/download_zarr.py, doc/changelog/changelog.rst, doc/changelog/v220b3.rst, pyproject.toml
----
📚 Documentation preview 📚: https://copernicusmarine--378.org.readthedocs.build/en/378/
=> Copernicusmarine pre release 2.2.0b3

doc/changelog/changelog.rst, doc/changelog/v220.rst, pyproject.toml
Please be aware that merging this PR will trigger the release process. Please check the following elements:
If not, please update 'main' branch or this PR if you are not targeting the 'main' branch.
----
📚 Documentation preview 📚: https://copernicusmarine--382.org.readthedocs.build/en/382/
=> Copernicus Marine Toolbox Release v2.2.0

Makefile, copernicusmarine/download_functions/subset_xarray.py, doc/changelog/changelog.rst, doc/changelog/v221.rst, doc/changelog/v230.rst, tests/__snapshots__/test_cf_compliance.ambr, tests/test_cf_compliance.py
----
📚 Documentation preview 📚: https://copernicusmarine--384.org.readthedocs.build/en/384/
=> CMT-232 CMT-279 type valid range and get more attributes from zarr

pyproject.toml
Please be aware that merging this PR will trigger the pre-release process. Please check the following elements:
Please do not target 'main' as the changelog will not be kept for the release.
=> Copernicus Marine Toolbox Pre-Release v2.3.0b0

copernicusmarine/core_functions/custom_s3_store_zarr_v3.py, doc/changelog/v230.rst
Before merging this PR, ensure you have completed the following:
=> fix: non blocking operation in custom v3 zarr store

copernicusmarine/download_functions/download_zarr.py
Please be aware that merging this PR will trigger the pre-release process. Please check the following elements:
Please do not target 'main' as the changelog will not be kept for the release.
=> Copernicus Marine Toolbox Pre-Release v2.3.0b2
