tests/resources/request_files/test_subset_error_when_forced_service_does_not_exist.json
The dataset we used for testing when we don't have ARCO services has them now so I changed it
Only test/development specific
=> fix: change dataset for the tests

copernicusmarine/download_functions/subset_xarray.py, tests/test_warnings_subset_bounds.py
Resolving [issue 278](https://mercator-ocean.atlassian.net/browse/CMCS-278).
To do so, I made sure that the interval was returning the correct options, adding a function to be able to compute higher bounds. With the code as is it right now, it raises warning's when the user request is out of bounds.
I would suggest, though, that if the subset is complete (from [-180, 180[) this warning is not raised. This is actually not working this way, because if the user request is [-180,180] is will never get to 180... I think the fix could be useful.
=> Created a function to be able to compute the higher bound

copernicusmarine/download_functions/common_download.py, tests/test_python_interface.py
Fixing the default _FillValue attribute reported in error [CMCS-361](https://mercator-ocean.atlassian.net/browse/CMCS-361).
Inspired in the solution proposed in the same ticket and in [this stack-overflow issue](https://stackoverflow.com/questions/45693688/xarray-automatically-applying-fillvalue-to-coordinates-on-netcdf-output/45696423#45696423).
When downloading the data, before passing it to the NetCDF file, the encoding is applied. 
Hope the definition of the dictionary is good enough with the type-written format.
=> default _Fillvalue attribute

tests/test_python_interface.py
Added the test with `netcdf_compression_enabled`flag set to true and some minor corrections to [PR-60](https://github.com/mercator-ocean/copernicus-marine-toolbox/pull/60).
Now, also without having trouble within the branches.
=> Added test with compression enabled

copernicusmarine/download_functions/common_download.py, tests/test_python_interface.py
Fixing bug [CMT-6](https://cms-change.atlassian.net/browse/CMT-6).
Wrong units when encoding to netcdf.
When setting `encoding={'time': {'_FillValue': None}}` XArray is losing the information for the rest, like the units or the calendar.
=> fix: wrong units in encoding

copernicusmarine/core_functions/utils.py, copernicusmarine/download_functions/subset_xarray.py
Seems like `astype(int)` from `numpy.datetime64` is returning completely different results on Windows than on Unix creating two bugs
https://cms-change.atlassian.net/browse/CMT-9
and https://cms-change.atlassian.net/browse/CMT-8
=> fix: change astype int to use datetime

copernicusmarine/catalogue_parser/catalogue_parser.py
Because the roles in stac of a wmts asset is "visual"
=> fix: show wmts in describe

copernicusmarine/core_functions/services_utils.py
Trying to solve deprecation warnings, raised in [CMT-5](https://cms-change.atlassian.net/browse/CMT-5) reported in [Issue in dfm-tools](https://github.com/Deltares/dfm_tools/issues/803).
We will need to process a little bit better the aiohttp.ClientSession() but this solves the first and easiest error.
=> chore: deleting logger.warn

copernicusmarine/catalogue_parser/catalogue_parser.py, copernicusmarine/catalogue_parser/request_structure.py, copernicusmarine/command_line_interface/exception_handler.py, copernicusmarine/command_line_interface/group_describe.py, copernicusmarine/command_line_interface/group_get.py, copernicusmarine/command_line_interface/group_login.py, copernicusmarine/command_line_interface/group_subset.py, copernicusmarine/core_functions/credentials_utils.py, copernicusmarine/core_functions/custom_open_zarr.py, copernicusmarine/core_functions/deprecated.py, copernicusmarine/core_functions/describe.py, copernicusmarine/core_functions/environment_variables.py, copernicusmarine/core_functions/get.py, copernicusmarine/core_functions/login.py, copernicusmarine/core_functions/services_utils.py, copernicusmarine/core_functions/subset.py, copernicusmarine/core_functions/utils.py, copernicusmarine/core_functions/versions_verifier.py, copernicusmarine/download_functions/common_download.py, copernicusmarine/download_functions/download_arco_series.py, copernicusmarine/download_functions/download_original_files.py, copernicusmarine/download_functions/subset_xarray.py, copernicusmarine/download_functions/utils.py, copernicusmarine/logging_conf.py
Fix https://cms-change.atlassian.net/browse/CMT-55
=> chore: change name logger to fit with the name of the library

copernicusmarine/core_functions/utils.py, tests/test_command_line_interface.py, tests/test_python_interface.py
fix [CMT-85]( https://cms-change.atlassian.net/browse/CMT-85)
Interestingly it seems like Windows does not support date before 1970. Hence the bug described in CMT-85 where the open dataset tries to set a valid min in 1950
=> fix: windows doesnt accept timestamp before 1970

copernicusmarine/download_functions/subset_xarray.py, tests/test_command_line_interface.py, tests/test_python_interface.py
Following the discussion in [CMT-53](https://cms-change.atlassian.net/browse/CMT-53), I deleted the valid_min and valid_max attributes for the dimensions. 
Still needs to be determined if we want to add min or max values as suggested, but it looks like we don't retrieve such values from the metadata...
=> Deleting valid_min and valid_max attributes

copernicusmarine/download_functions/subset_xarray.py
In [Pull 127](https://github.com/mercator-ocean/copernicus-marine-toolbox/pull/127) we discovered that the values of `valid_min` and `valid_max` didn't have the same format as the variable, which isn't consistent with the CF convention.
I've created this changes to make sure that the types of the values are correct.
=> Adapt type of valid minmax

copernicusmarine/core_functions/utils.py, tests/test_utility_functions.py
A fix that was found thanks to the tests
This would return the wrong start value: 
```
copernicusmarine subset -i cmems_mod_blk_wav_my_2.5km_PT1H-i --end-datetime 1980-09-10 -v VCMX
```
=> fix: not converting properly timestamp

copernicusmarine/download_functions/subset_xarray.py
Found a bug with full test datasets where the decimals were not correctly handled
this would fail: 
```
copernicusmarine subset -i cmems_obs_oc_blk_bgc_tur-spm-chl_nrt_l3-hr-mosaic_P1D-m -x 26.000661375661405 -X 26.000661375661405
```
=> fix: decimal not handled with modulus

copernicusmarine/catalogue_parser/models.py
We would set the minimun to the `admp_valid_start_date` whereas some datasets have values and hence we should return only the valid values for the time values. See an example: 
https://stac.marine.copernicus.eu/metadata/OCEANCOLOUR_ATL_BGC_L4_NRT_009_116/cmems_obs-oc_atl_bgc-pp_nrt_l4-multi-1km_P1M_202311/dataset.stac.json
=> fix: handle admp valid start index for retention period

copernicusmarine/download_functions/download_original_files.py
From ticket [CMT-108](https://cms-change.atlassian.net/browse/CMT-108), were a get was being done and the toolbox was taking so long, we thought that it might be interesting to add, as an output, some sort of information about the process that is being done underneath.
This might help users understand that, although it will take a while, it will eventually reach and download the files.
=> chore: update the output when listing files

copernicusmarine/python_interface/get.py, copernicusmarine/python_interface/subset.py
Fix: [CMT-20](https://cms-change.atlassian.net/browse/CMT-120)
=> fix: datasetid not mandatory in py inter for consistency

doc/installation.rst
adding the link to the binaries in the documentation (now hardcoded version, later on will be linked to the latest stable release)
=> chore: add installation page

copernicusmarine/catalogue_parser/request_structure.py, copernicusmarine/command_line_interface/group_login.py, copernicusmarine/core_functions/deprecated.py, copernicusmarine/core_functions/deprecated_options.py, copernicusmarine/python_interface/describe.py, copernicusmarine/python_interface/get.py, copernicusmarine/python_interface/login.py, copernicusmarine/python_interface/open_dataset.py, copernicusmarine/python_interface/read_dataframe.py, copernicusmarine/python_interface/subset.py, tests/test_command_line_interface.py, tests/test_deprecated_options.py, tests/test_get_create_file_list.py
Add deprecation for options that will be deleted in v2. 
Added some different messages depending on the cases: 
- If it has a replacement already
- If it will be deleted or deprecated in the v2
- If it is only about the v2
=> chore: update the deprecation for v2

copernicusmarine/core_functions/subset.py, tests/test_command_line_interface.py
Even with `copernicusmarine subset --staging` the command was not getting the dataset from staging
Bug introduced when got rid of the cache
=> fix: subset was not using staging metadata

copernicusmarine/download_functions/subset_xarray.py
I am very surprise this hasn't been reported before, I guess a vast majority of the datasets follow the conventional names
=> fix: use coordinate equivalent

copernicusmarine/catalogue_parser/catalogue_parser.py
fix: https://cms-change.atlassian.net/browse/CMT-127
We now use the same convention as MyOcean and use the datasetID for dataset name when there are not default dataset part
=> fix: dataset name is datasetID if dataset have parts

copernicusmarine/command_line_interface/group_subset.py, copernicusmarine/download_functions/download_arco_series.py, doc/usage/subset-usage.rst, tests/__snapshots__/test_help_command_interface.ambr, tests/test_command_line_interface.py
With the help of xarray developers in [Issue #9783](https://github.com/pydata/xarray/issues/9783) we solved the issue with the encoding for netcdf datasets (it looked like it was already pretty well compressed and we were not sending all the information to the output).
I also changed the default value to 4 for the CLI subset because from [here](https://unidata.github.io/netcdf4-python/#netCDF4.Dataset.createVariable) it looked like the default compression value for xarray is also 4.
Looks like now, indeed, the 3 commands are saving the files with 'according' sizes:
```
copernicusmarine subset --dataset-id cmems_mod_glo_phy_my_0.083deg_P1D-m -v thetao -t 1993-01-01T00:00:00 -T 2020-12-31T23:59:59 -x -90 -X -85 -y -35 -Y -30 -z 0.49 -Z 1 --netcdf-compression-level 1 -f comlevel1.nc …
```
=> fix: netcdf compression solved

copernicusmarine/catalogue_parser/models.py, tests/test_describe.py
With the entrance of stereographic projections, the tests done on the describe need to be updated. Correcting the issues, when checking that there exists only one part -> there can now exist 2, if one of them is in the originalGrid (stereographic projection).
----
📚 Documentation preview 📚: https://copernicusmarine--220.org.readthedocs.build/en/220/
=> fix: updating tests

doc/installation.rst
Updating the binaries link in the documentation for the following release.
I'm not sure I like it fully because the link will not work properly for future pre-releases (that is also why I hardcoded them before). I will check it in the future.
----
📚 Documentation preview 📚: https://copernicusmarine--219.org.readthedocs.build/en/219/
=> fix: updating link for the binaries

copernicusmarine/core_functions/get.py, copernicusmarine/core_functions/services_utils.py, doc/usage/get-usage.rst, tests/test_get_sync.py
When we have more than one part, allow still the syncing of the options. Correcting [CMT-151](https://cms-change.atlassian.net/browse/CMT-151) also for version 2 of the toolbox (and even allowing it for several parts).
Currently, the tests are done on the staging area, as in PRD the datasets have been removed for the moment. We will need to update this.
----
📚 Documentation preview 📚: https://copernicusmarine--240.org.readthedocs.build/en/240/
=> chore: syncing parts allowed

copernicusmarine/download_functions/subset_xarray.py
Fixing [CMT-163](https://cms-change.atlassian.net/jira/software/c/projects/CMT/issues/CMT-163?filter=allissues&jql=project%20%3D%20%22CMT%22%20ORDER%20BY%20created%20DESC). If the minimum or maximum is not set, and the other limit exceeds the coordinates, make sure that the error we throw makes sense.
----
📚 Documentation preview 📚: https://copernicusmarine--242.org.readthedocs.build/en/242/
=> fix: updating out-of-bounds message

copernicusmarine/download_functions/utils.py
Fixing bug [CMT-161](https://cms-change.atlassian.net/browse/CMT-161), where because the dataset is OMI, it has a values set, but those are not numbers but rather regions -> hard to estimate the size then. I just skip them, as if the values were not correctly set.
----
📚 Documentation preview 📚: https://copernicusmarine--243.org.readthedocs.build/en/243/
=> chore: solving chunk search for omi

copernicusmarine/command_line_interface/group_subset.py, copernicusmarine/core_functions/models.py, copernicusmarine/download_functions/download_arco_series.py, doc/usage/subset-usage.rst, tests/__snapshots__/test_help_command_interface.ambr, tests/test_command_line_interface.py, tests/test_python_interface.py
Trying to solve issue [CMT-164](https://cms-change.atlassian.net/browse/CMT-164). To do that, only keep scale factor and offset but remove other types in the encoding (I think it was `type`which was causing the problems).
----
📚 Documentation preview 📚: https://copernicusmarine--241.org.readthedocs.build/en/241/
=> fix: correcting issues with compression

copernicusmarine/download_functions/download_arco_series.py, tests/test_command_line_interface.py, tests/test_python_interface.py
Okay, updating the `encoding` to contain: `add_offset, scale_factor, type and _FillValue`.
It looks like it is not breaking as I thought, so looks good. Indeed with the type, the compression seems to be a little bit improved.
----
📚 Documentation preview 📚: https://copernicusmarine--249.org.readthedocs.build/en/249/
=> fix: all in the encoding

copernicusmarine/core_functions/credentials_utils.py, copernicusmarine/core_functions/login.py, copernicusmarine/core_functions/sessions.py
fix [CMT-178](https://cms-change.atlassian.net/browse/CMT-178)
Allow the login errors to be clearer especially when the user aborts when asked to confirm
----
📚 Documentation preview 📚: https://copernicusmarine--254.org.readthedocs.build/en/254/
=> fix: error logins are now more readable and pythonic

copernicusmarine/download_functions/download_original_files.py
fix a bug where the sync-delete would fail if not file would be found (for example with a filter that does not match) 
----
📚 Documentation preview 📚: https://copernicusmarine--255.org.readthedocs.build/en/255/
=> fix: sync fails if no data to download

.github/workflows/binaries.yml, .github/workflows/binary-windows.yml, .github/workflows/release.yml
We noticed the the creation of the binaries might finish before the release is done so trying to do the binaries after the release
----
📚 Documentation preview 📚: https://copernicusmarine--264.org.readthedocs.build/en/264/
=> chore: trigger the binaries after the release

doc/changelog/v2.rst
Had a typo with `--force-dataset-part` twice
----
📚 Documentation preview 📚: https://copernicusmarine--265.org.readthedocs.build/en/265/
=> doc: deprecated force service

tests/test_dataset_version_selection.py
There was this dataset that was being used for the tests that just ended the double-dissemination process. I'm updating the `dataset_id` to be able to keep the tests without such dataset. The new `dataset_id` contains the specifications of the old one: to only have one version, called `default`. It looks that this was the important part and the one taken into account to change the test.
----
📚 Documentation preview 📚: https://copernicusmarine--270.org.readthedocs.build/en/270/
=> Update the tests also in v2

.github/workflows/binary-test.yml, Makefile, conda_environment_binary.yaml
Trying to solve the latest crash with the binaries.
----
📚 Documentation preview 📚: https://copernicusmarine--274.org.readthedocs.build/en/274/
=> manually add dependency deprecated when building binaries

copernicusmarine/download_functions/download_arco_series.py, copernicusmarine/download_functions/utils.py, tests/test_cf_compliance.py, tests/test_command_line_interface.py, tests/test_utils.py
We discovered some incongruence between the size of the dataset and our estimation. Although it seems that the proposed new method is not bullet-proof either, it looks like it will be more consistent in the estimation.
Trying to solve issues [CMT-175](https://cms-change.atlassian.net/browse/CMT-175) and [CMT-171](https://cms-change.atlassian.net/browse/CMT-171).
----
📚 Documentation preview 📚: https://copernicusmarine--275.org.readthedocs.build/en/275/
=> better estimating the file size

doc/changelog/changelog.rst, doc/changelog/v201.rst
Change log for version 2.0.1
----
📚 Documentation preview 📚: https://copernicusmarine--279.org.readthedocs.build/en/279/
=> chore: add changelog

.github/workflows/binaries.yml, .github/workflows/binary-test.yml, Makefile, doc/conf.py, doc/installation.rst, tests_binaries/test_basic_commands_binaries.py
From https://github.com/actions/runner-images/issues/11101 we know we will need to update the runner.
I finally chose to just update the runner rather than just deleting it, so we keep having 2 versions for ubuntu.
----
📚 Documentation preview 📚: https://copernicusmarine--290.org.readthedocs.build/en/290/
=> Updating ubuntu runner

copernicusmarine/download_functions/download_sparse.py, doc/installation.rst, doc/usage/subset-usage.rst, poetry.lock, pyproject.toml, tests/__snapshots__/test_dependencies_updates.ambr, tests/test_sparse_subset.py
Rename correctly the columns
Refactor the code not to repeat it.
Also decided to have the parquet as only one file and loaded in memory to simplify the result the user receives
----
📚 Documentation preview 📚: https://copernicusmarine--300.org.readthedocs.build/en/300/
=> feat: update arcosparse to v0.3.0

doc/installation.rst, poetry.lock, pyproject.toml, tests/__snapshots__/test_dependencies_updates.ambr
arcosparse 0.3.1 should fix problems that were encountered on Windows platforms 
----
📚 Documentation preview 📚: https://copernicusmarine--302.org.readthedocs.build/en/302/
=> fix: update arcosparse to solve windows bugs

copernicusmarine/catalogue_parser/models.py, doc/usage/describe-usage.rst, doc/usage/stereo_subset.ipynb, doc/usage/subset-usage.rst
Re-read the modified parts of the documentation and updated them accordingly
----
📚 Documentation preview 📚: https://copernicusmarine--314.org.readthedocs.build/en/314/
=> Correct documentation typos for the spare and stereographic subsetting

doc/usage/stereo_subset.ipynb
The stereographic subset page seems to have this little typography error.
----
📚 Documentation preview 📚: https://copernicusmarine--318.org.readthedocs.build/en/318/
=> [fix] correcting a typography in the documentation

copernicusmarine/python_interface/open_dataset.py, copernicusmarine/python_interface/subset.py
Update the documentation, as in some parts the default was still set to 100 for the `chunk_size_limit` feature.
I think those are the places pointed out in https://github.com/mercator-ocean/copernicus-marine-toolbox/issues/267 . Thanks again :)
----
📚 Documentation preview 📚: https://copernicusmarine--325.org.readthedocs.build/en/325/
=> fix: default to -1 for chunk_size_limit

copernicusmarine/download_functions/download_zarr.py, tests/test_python_interface.py
Pass along the units also in the enconding dict, so that they are kept for the variables.
----
📚 Documentation preview 📚: https://copernicusmarine--333.org.readthedocs.build/en/333/
=> fix: pass units in the encoding

copernicusmarine/command_line_interface/group_subset.py, copernicusmarine/command_line_interface/utils.py, copernicusmarine/core_functions/click_custom_class.py, tests/__snapshots__/test_help_command_interface.ambr
We found out that the latest release from click crashes with our deprecated options, see [CMT-245](https://cms-change.atlassian.net/browse/CMT-245).
As discovered by Renaud, in the argument initialisation there is a boolean that is `deprecated` so better keep the naming different. This looks to solve the current problem.
----
📚 Documentation preview 📚: https://copernicusmarine--340.org.readthedocs.build/en/340/
[CMT-245]: https://cms-change.atlassian.net/browse/CMT-245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> deprecated to custom deprecated

copernicusmarine/core_functions/custom_open_zarr.py, copernicusmarine/core_functions/custom_s3_store_zarr_v3.py
fix [issue reported here ](https://github.com/zarr-developers/zarr-python/issues/3189)
----
📚 Documentation preview 📚: https://copernicusmarine--370.org.readthedocs.build/en/370/
=> fix: read only open zarr

doc/installation.rst
We want to specify the zarr dependencies with xarray and with the toolbox itself. 
Maybe also we want to patch the other minor versions of the toolbox but let's see.
----
📚 Documentation preview 📚: https://copernicusmarine--371.org.readthedocs.build/en/371/
=> [update] zarr documentation

tests/test_get_direct_download.py, tests/test_login.py
Modify tests to pass before removing old authentication system. We need to keep it in mind to make sure everything works nicely afterwards.
----
📚 Documentation preview 📚: https://copernicusmarine--379.org.readthedocs.build/en/379/
=> modify tests to pass before removing old authentication system

copernicusmarine/core_functions/credentials_utils.py, doc/installation.rst, doc/usage/login-usage.rst
Remove the mentioning of the old authentication system from the error.
Do you think that we should say something, between now and when we remove the old-car completely from the code, about checking that the credentials are okey? Or would it be a problem onwards, once solved?
Let me know what you think!
----
📚 Documentation preview 📚: https://copernicusmarine--380.org.readthedocs.build/en/380/
=> [doc-update] remove old auth system mention

.github/workflows/tests_on_oss.yml
Should be triggered on `pre-release` not `pre-releases`
----
📚 Documentation preview 📚: https://copernicusmarine--376.org.readthedocs.build/en/376/
=> fix: typo in the branches triggered for tests on oss

doc/changelog/v221.rst, doc/usage/get-usage.rst, doc/usage/shared-options.rst, doc/usage/subset-usage.rst
In relation to [CMT-284](https://cms-change.atlassian.net/browse/CMT-284) we want to make sure that the responses that are showed in the documentation are accordingly to the current version.
Maybe we should think of some way to keep the documentation up to date without having to think about it too much, no? 
Also, I removed the `--log-level DEBUG` because I feel like it is too verbose.
[CMT-284]: https://cms-change.atlassian.net/browse/CMT-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
----
📚 Documentation preview 📚: https://copernicusmarine--383.org.readthedocs.build/en/383/
=> [doc-update] update old documentation CMT-284
